### ISSUE TITLE
Arguments passed to custom grader

### ISSUE THREAD

**Issue by knolleary** [coursera/programming-assignments-demo#11]
Hi,

I'm creating a custom grader and wanted to check what arguments it will get passed when invoked.

From [`exampleGrader.sh`](https://github.com/coursera/programming-assignments-demo/blob/master/custom-graders/DemoAssignmentGrader/GraderFiles/executeGrader.sh) I infer it will get called with arguments:

```
partId <partId> userId <userId> filename <original_filename>
```

but I couldn't find that formally documented anywhere. Is this correct?

**Comment by billboyd201** [comment]
I've just been through the process. Those are the three things passed along with student submission. If you'd like, you can call and I can pass on other tips. 860.539.8144 cell. Catching plane in 1 hour for 4 hrs. Available now or later. Out of country starting sat for a week though.
Bill Boyd
Wesleyan Univ.
Connecticut

Sent from my Verizon Wireless 4G LTE smartphone. ...nnk

-------- Original message --------

**Comment by ngarg-coursera** [comment]
Hi,

We've put most of the information as comments within Dockerfile and executeGrader.sh along with the README within custom-graders directory.

Thanks for offering to help out Bill.

Also, feel free to reach out to programming@coursera.org if you have any other questions regarding the grader creation process.

**Comment by knolleary** [comment]
Ok, so it sounds like I'm correct in my reading of executeGrader.sh.

Personally I think it would be useful to provide an explicit example under Question 3 of the [custom-grade readme](https://github.com/coursera/programming-assignments-demo/blob/master/custom-graders/README.md#question-3-can-a-single-grader-be-used-to-grade-multiple-programming-assignment-parts) rather than rely on developers having to infer it from the code.

**Comment by ngarg-coursera** [comment]
Thanks for the suggestion. I'll make a note to add it soon.
